name = "froggy-telegram-bot"
main = "src/bot.ts"
compatibility_date = "2025-09-06"

# IMPORTANT: Remember to update cron-triggers.ts with the same cron expressions
[triggers]
crons = [
    "20 15 * * *",
    "20 15 * * 5",
    ]

[[d1_databases]]
binding = "DB"
database_name = "level-up-database"
database_id = "c4887c48-b00b-4fd9-8547-1fe06e323ff9"

[observability]
enabled = true
head_sampling_rate = 1
