name = "froggy-telegram-bot"
main = "src/bot.ts"
compatibility_date = "2025-09-06"

[triggers]
# Every Thursday at 17:00 (UTC)
crons = ["0 17 * * 4"]

[[d1_databases]]
binding = "DB"
database_name = "level-up-database"
database_id = "c4887c48-b00b-4fd9-8547-1fe06e323ff9"